---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tunnel
  namespace: argocd
spec:
  project: default
  source:
    path: cloudflare/tunnel/overlays/production
    repoURL: https://github.com/lengors/lengy.git
    targetRevision: main
  destination:
    namespace: cloudflare
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      selfHeal: true
      prune: true