---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: tunnel
namespace: cloudflare
secretGenerator:
  - name: tunnel
    envs:
      - secret/.env
resources:
  - "../../base"
  - "application.yaml"
