---
apiVersion: secrets.hashicorp.com/v1beta1
kind: HCPVaultSecretsApp
metadata:
  name: tunnel
  namespace: cloudflare
spec:
  appName: lengy-production
  hcpAuthRef: cloudflare/tunnel
  destination:
    create: true
    labels:
      hvs: "true"
    name: tunnel
  refreshAfter: 1h
