---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

resources:
  - base/namespace.yaml
  - base/application.yaml
  - https://raw.githubusercontent.com/argoproj/argo-cd/v2.10.2/manifests/install.yaml