---
apiVersion: secrets.hashicorp.com/v1beta1
kind: HCPVaultSecretsApp
metadata:
  name: traefik-system
  namespace: traefik-system
spec:
  appName: traefik-system-production
  hcpAuthRef: traefik-system/traefik-system
  destination:
    create: true
    labels:
      hvs: "true"
    name: traefik-system
  refreshAfter: 1h
