---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: argocd
resources:
  - "../../base"
  - "applications/argocd/application.yaml"
  - "applications/vault/secrets-operator/application.yaml"