---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: secrets-operator
resources:
  - "../../../base"
helmCharts:
  - name: vault-secrets-operator
    namespace: vault
    repo: https://helm.releases.hashicorp.com
    releaseName: secrets-operator
    version: 0.5.2
    includeCRDs: true
    valuesMerge: override
    valuesFile: values.yaml
